### ISSUE TITLE
Cant make a want.

### ISSUE THREAD

**Issue by afghan2007** [ArtixAllMighty/Rpg-Addon-BerserkMageArcher#1]
I'm trying the new 10.2 version of this mod barb/mage/archer.  Every time I enchant the sensibility stick with arcane affinity and place it my hot bar, it converts to a normal stick.  I also try the spells and even when the name of the spell is displayed next to the wand after speaking it, left clicking doesn't seem to do anything.

**Comment by afghan2007** [comment]
Forge ver: 10.2-12.18.2.2114
BAM: first and so far only mod for 10.2
Minecraft 10.2

**Comment by ArtixAllMighty** [comment]
that's because you need to actually craft the stick. it needs the core items to be enchanted. (and other internal reasons)

**Comment by afghan2007** [comment]
I have the wand and the wands down they seem to be working.  All gesture are abstract at best and I can right click anything with the want .  What am I not doing right to cast spells? This a version 10.2.  Do I need to shift+right-click.  Nothing seems to work.  My newly crafted wand has my Name taged to it and the spell name shows up when I say it but nothing comes out of the wand.
