### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by MagicCheese1** [ArtixAllMighty/Rpg-Addon-BerserkMageArcher#12]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  SSLoadingPlugin (6-SereneSeasons.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.18_mc1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  CreativePatchingLoader (CreativeCore_v1.9.36_mc1.12.2.jar)
  CXLibraryCore (CXLibrary-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/16/19 10:48 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at subaraki.BMA.handler.event.BmaEventHandler.countFreezeTimerServer(BmaEventHandler.java:267)
	at subaraki.BMA.handler.event.BmaEventHandler.onWorldTick(BmaEventHandler.java:82)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_407_BmaEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2727169552 bytes (2600 MB) / 5037883392 bytes (4804 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9216m -XX:MaxPermSize=512m
	IntCache: cache: 3, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                                | Signature                                |
	|:------ |:-------------------- |:----------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                         | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | modpack.jar                                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2838      | modpack.jar                                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy    | 1.0.0             | minecraft.jar                                         | None                                     |
	| LCHIJA | itemphysic           | 1.4.0             | minecraft.jar                                         | None                                     |
	| LCHIJA | dsurroundcore        | 3.5.4.3           | minecraft.jar                                         | None                                     |
	| LCHIJA | jei                  | 4.15.0.287        | 11-jei.jar                                            | None                                     |
	| LCHIJA | buildcraftlib        | 7.99.24.1         | 12-BuildCraftMod.jar                                  | None                                     |
	| LCHIJA | buildcraftcore       | 7.99.24.1         | 12-BuildCraftMod.jar                                  | None                                     |
	| LCHIJA | buildcraftbuilders   | 7.99.24.1         | 12-BuildCraftMod.jar                                  | None                                     |
	| LCHIJA | buildcrafttransport  | 7.99.24.1         | 12-BuildCraftMod.jar                                  | None                                     |
	| LCHIJA | buildcraftsilicon    | 7.99.24.1         | 12-BuildCraftMod.jar                                  | None                                     |
	| LCHIJA | buildcraftcompat     | 7.99.24.1         | 12-BuildCraftMod.jar                                  | None                                     |
	| LCHIJA | buildcraftenergy     | 7.99.24.1         | 12-BuildCraftMod.jar                                  | None                                     |
	| LCHIJA | buildcraftfactory    | 7.99.24.1         | 12-BuildCraftMod.jar                                  | None                                     |
	| LCHIJA | buildcraftrobotics   | 7.99.24.1         | 12-BuildCraftMod.jar                                  | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.5.5      | 18-journeymap.jar                                     | None                                     |
	| LCHIJA | bspkrscore           | at_0.9            | 25-TreeCapitator-Mod.jar                              | None                                     |
	| LCHIJA | treecapitator        | at_0.9            | 25-TreeCapitator-Mod.jar                              | None                                     |
	| LCHIJA | cfm                  | 6.3.0             | 26-cfm-6.3.0-mc.jar                                   | None                                     |
	| LCHIJA | codechickenlib       | 3.2.2.353         | 28-CodeChickenLib.jar                                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks        | 2.4.1.73          | 27-ChickenChunks-Mod.jar                              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ironchest            | 1.12.2-7.0.67.844 | 30-Iron-Chests-Mod.jar                                | None                                     |
	| LCHIJA | trashslot            | 8.4.10            | 31-TrashSlot.jar                                      | None                                     |
	| LCHIJA | fastfurnace          | 1.3.1             | 35-FastFurnace.jar                                    | None                                     |
	| LCHIJA | ichunutil            | 7.2.1             | iChunUtil-1.12.2-7.2.1.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | backtools            | 7.0.1             | 38-BackTools-1.12.2-7.0.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | carryon              | 1.12.2            | 41-CarryOn+MC1.12.2+v1.12.2.jar                       | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | eleccore             | 1.9.452           | ElecCore-1.12.2-1.9.452.jar                           | None                                     |
	| LCHIJA | huds                 | #VERSION#         | 42-Huds-1.12.2-1.0.3.jar                              | None                                     |
	| LCHIJA | ambientsounds        | 3.0               | 43-AmbientSounds_v3.0.9_mc1.12.2.jar                  | None                                     |
	| LCHIJA | mobdismemberment     | 7.0.0             | 44-MobDismemberment-1.12.2-7.0.0.jar                  | None                                     |
	| LCHIJA | stellarapi           | 1.12.2-0.4.2.9    | 49-Stellar+API-1.12.2-0.4.2.9.jar                     | None                                     |
	| LCHIJA | stellarsky           | 1.12.2-0.5.2.8    | 46-Stellar+Sky-1.12.2-0.5.2.8.jar                     | None                                     |
	| LCHIJA | epicsiegemod         | 13.164            | 52-Epic-Siege-Returns-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | chameleon            | 1.12-4.1.3        | 62-Chameleon-Library-1.12.jar                         | None                                     |
	| LCHIJA | storagedrawers       | 1.12-5.3.5        | 54-StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
	| LCHIJA | subcommonlib         | 1.2.0.1           | 64-subcommonlib-sublib-1.12.2-1.2.0.4.jar             | None                                     |
	| LCHIJA | rpginventory         | 1.12.2            | 63-Rpg-Inventory-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | beastmaster          | $version          | 55-Class-Armor-Mod-Beast-Master-1.12.2.jar            | None                                     |
	| LCHIJA | bma_addon            | 1.11.2 4.0.3.0    | 55-Class-Armor-Mod-Berserker-Mage-Archer-1.12 (1).jar | None                                     |
	| LCHIJA | umbralux             | 1.12.2            | 55-Class-Armor-Mod-Berserker-Mage-Archer-1.12 (2).jar | None                                     |
	| LCHIJA | baubles              | 1.5.2             | Baubles-Mod-1.12.2.jar                                | None                                     |
	| LCHIJA | xreliquary           | 1.12.2-1.3.4.796  | 56-Reliquary-1.12.2-1.3.4.796.jar                     | None                                     |
	| LCHIJA | sereneseasons        | 1.2.16            | 6-SereneSeasons.jar                                   | None                                     |
	| LCHIJA | valkyrielib          | 1.12.2-2.0.20.1   | 65-valkyrielib-1.12.2-2.0.20.1.jar                    | None                                     |
	| LCHIJA | universalmodifiers   | 1.12.2-1.0.16.1   | 65-valkyrielib-1.12.2-2.0.20.1.jar                    | None                                     |
	| LCHIJA | movinglightsource    | 1.0.15            | 7-movinglightsource.jar                               | None                                     |
	| LCHIJA | additionalstructures | 2.2.2             | 8-Rex's-Additional-Structures.jar                     | None                                     |
	| LCHIJA | additionalpipes      | 6.0.0.8           | Additional-Pipes-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | chunkpregenerator    | 2.1               | Chunk+Pregenerator+V1.12-2.2.jar                      | None                                     |
	| LCHIJA | extendedrenderer     | v1.0              | CoroUtil-1.12.2.jar                                   | None                                     |
	| LCHIJA | coroutil             | 1.12.1-1.2.19     | CoroUtil-1.12.2.jar                                   | None                                     |
	| LCHIJA | configmod            | v1.0              | CoroUtil-1.12.2.jar                                   | None                                     |
	| LCHIJA | creativecore         | 1.9.9             | CreativeCore_v1.9.36_mc1.12.2.jar                     | None                                     |
	| LCHIJA | cxlibrary            | 1.6.1             | CXLibrary-1.12.2.jar                                  | None                                     |
	| LCHIJA | ptrmodellib          | 1.0.3             | PTRLib-1.0.3.jar                                      | None                                     |
	| LCHIJA | props                | 2.6.3             | DecoCraft-Mod-1.12.2.jar                              | None                                     |
	| LCHIJA | defiledlands         | 1.4.2             | defiledlands-1.12.2-1.4.2.jar                         | None                                     |
	| LCHIJA | dynamictrees         | 1.12.2-0.9.6      | DynamicTrees-1.12.2-0.9.6.jar                         | None                                     |
	| LCHIJA | traverse             | 1.6.0             | Traverse-1.12.2-1.6.0-69.jar                          | None                                     |
	| LCHIJA | dttraverse           | 1.5               | dttraverse-1.5.jar                                    | None                                     |
	| LCHIJA | enhancedvisuals      | 1.0               | EnhancedVisuals_v1.2.4_mc1.12.2.jar                   | None                                     |
	| LCHIJA | fbp                  | 2.4.1             | FancyBlockParticles-1.12.x-2.4.1.jar                  | None                                     |
	| LCHIJA | waila                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	| LCHIJA | morefurnaces         | 1.10.5            | More-Furnaces-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | orecore              | 1.4.1             | Ore-Core-Mod-1.12.2.jar                               | None                                     |
	| LCHIJA | pvj                  | 1.6.4             | ProjectVibrantJourneys-1.12.2-1.6.4.jar               | None                                     |
	| LCHIJA | torchlever           | 1.0               | TorchLever1.12.2-1.0.jar                              | None                                     |
	| LCHIJA | toughasnails         | 3.1.0.139         | ToughAsNails-1.12.2-3.1.0.139-universal.jar           | None                                     |
	| LCHIJA | llibrary             | 1.7.18            | 34-LLibrary.jar                                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | orelib               | 3.5.2.2           | OreLib-1.12.2-3.5.2.2.jar                             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround            | 3.5.4.3           | DynamicSurroundings-1.12.2-3.5.4.3.jar                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | eleccoreloader       | 1.9.452           | ElecCore-1.12.2-1.9.452.jar                           | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SSLoadingPlugin (6-SereneSeasons.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ItemPatchingLoader (ItemPhysic_Full_1.4.18_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
CreativePatchingLoader (CreativeCore_v1.9.36_mc1.12.2.jar)
  
CXLibraryCore (CXLibrary-1.12.2.jar)
  cubex2.cxlibrary.CoreModTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by AbsolemJackdaw** [comment]
where you using the hammer by any chance ?
