### ISSUE TITLE
advanced bow

### ISSUE THREAD

**Issue by wilsondgonzales** [ArtixAllMighty/Rpg-Addon-BerserkMageArcher#3]
need some help with the bow. i can't seem to make it draw. double clicking to switch how it's held works and the crossbow works. i'm fully armored with headless arrows and i can't seem to make it work

**Comment by ArtixAllMighty** [comment]
you actually need regular vanilla arrows to draw the advanced bow.
headless arrows are a way of making more arrows with less. 
I'm planning on adding more tiers of arrows alter one, and headless arrows will be the base of all of them

**Comment by ArtixAllMighty** [comment]
I've updated the wiki to include the information that headless arrows arent shootable, and that advacned bows requier vanilla arrows to be drawn.
