### ISSUE TITLE
Magic Carpets Crash

### ISSUE THREAD

**Issue by JuicebQx** [ArtixAllMighty/Rpg-Addon-BerserkMageArcher#5]
I've found that in 1.12.2, if you ride a magic carpet into the roof of an area, you crash a server. Just thought I should let you know

**Comment by ArtixAllMighty** [comment]
define the roof ?

**Comment by JuicebQx** [comment]
Any block above the player while they ride the carpet. Riding directly into a block above the player will crash a server

**Comment by ArtixAllMighty** [comment]
got a log ? apart from that, will look into it

**Comment by JuicebQx** [comment]
[crash-2018-01-22_15.18.43-server.txt](https://github.com/ArtixAllMighty/Rpg-Addon-BerserkMageArcher/files/1657400/crash-2018-01-22_15.18.43-server.txt)
