### ISSUE TITLE
BMA hammer still crashes servers in 1.12.2

### ISSUE THREAD

**Issue by JuicebQx** [ArtixAllMighty/Rpg-Addon-BerserkMageArcher#6]
Hey, while you're working on stuff, I just tested the berserker hammer again, it crashes games, and the server on occasion

**Comment by ArtixAllMighty** [comment]
log ?

**Comment by ArtixAllMighty** [comment]
also, if you have discord : 

https://discord.gg/8MEdFZh

**Comment by JuicebQx** [comment]
[crash-2018-01-22_19.53.05-server.txt](https://github.com/ArtixAllMighty/Rpg-Addon-BerserkMageArcher/files/1657496/crash-2018-01-22_19.53.05-server.txt)

Here's the crash text
