### ISSUE TITLE
arcane sensible stick with arcane affinity doesn't transform when holding

### ISSUE THREAD

**Issue by lag42** [ArtixAllMighty/Rpg-Addon-BerserkMageArcher#7]
My ign is lag42 so it might have to do with the fact that my fourth letter is a number

**Comment by AbsolemJackdaw** [comment]
I'm going to need a log for that. 
numbers are handled as special characters and should account as '1'

**Comment by lag42** [comment]
I tried to obtain the log on a cleaner instance and it worked fine, guess another mod is screwing with it, I really should be more careful before I submit an issue
